version: 2
project_name: grafcli

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: graf
    binary: graf
    main: .
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/nabooai/grafcli/cmd.Version={{.Version}}

archives:
  - id: graf
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: archive

changelog:
  sort: asc
  filters:
    exclude: ['^docs:', '^test:', '^chore:']
